name: "Taggear Imagen de docker"

inputs:
  image_name:
    description: "Nombre de la imagen"
    required: true
  version:
    description: "Versión de la imagen"
    required: true
    
outputs:
  tagged:
    description: "Nombre completo para la imagen taggeada"

runs:
  using: "composite"
  steps:
    - name: "Nombre completo Imagen"
      id: taggear
      shell: bash
      run: |
        tagged_image="${{ inputs.image_name }}:${{ inputs.version }}"
        echo "Tagged image: $tagged_image"
        echo "tagged=${tagged_image}" >> $GITHUB_ENV
   
