name: "Taggear Imagen de docker"

outputs:
  tagged:
    description: "Nombre completo para la imagen taggeada"
    value: "${{steps.taggear.outputs.tagged}}"

runs:
  using: "composite"
  steps:
    - name: "Extraer versión"
      id: version
      shell: bash
      run: |
        version=$(jq -r '.version' ./package.json)
        echo "Image version: $version"
        echo  "version=${version}" >> $GITHUB_OUTPUT

    - name: "Extraer nombre de la imagen"
      id: image_name
      shell: bash
      run: |
        image_name=$(jq -r '.name' ./package.json)
        echo "Image name: $image_name"
        echo "image_name=${image_name}" >> $GITHUB_OUTPUT
        
    - name: "Nombre completo Imagen"
      id: taggear
      shell: bash
      run: |
        tagged_image="${{  steps.image_name.outputs.image_name }}:${{ steps.version.outputs.version}}"
        echo "Tagged image: $tagged_image"
        echo "tagged=${tagged_image}" >> $GITHUB_OUTPUT
  
