name: "Taggear Imagen de docker"

inputs:
  image_name:
    description: "Nombre de la imagen"
    required: true

outputs:
  tagged:
    description: "Nombre completo para la imagen taggeada"
    value: "${{steps.taggear.outputs.tagged}}"

runs:
  using: "composite"
  steps:
    - name: "Extraer versión"
      id: version
      shell: bash
      run: |
        version=$(jq -r '.version' ./package.json)
        echo "Image version: $version"
        echo  "version=${version}" >> $GITHUB_OUTPUT
        
    - name: "Nombre completo Imagen"
      id: taggear
      shell: bash
      run: |
        tagged_image="${{ inputs.image_name }}:${{ steps.determine_version.outputs.version}}"
        echo "Tagged image: $tagged_image"
        echo "tagged=${tagged_image}" >> $GITHUB_OUTPUT
  
