name: "Extraer versión"
outputs:
  version:
    description: "version"
    value: "${{steps.version.outputs.version}}"

runs:
  using: "composite"
  steps:
    id: version
    shell: bash
    run: |
        version=$(jq -r '.version' ./package.json)
        echo "Image version: $version"
        echo  "version=${version}" >> $GITHUB_OUTPUT

  
