name: "Enviroment"

outputs:
  environment:
    description: "Entorno donde me encuentro"
    value: "${{steps.set-env.outputs.environment}}"
    
runs:
  using: "composite"
  steps:
    - name: Imprimir rama del push
      shell: bash
      run: echo "El push se realizó en la rama ${{ github.ref_name }}"
        
    - name: Definir entorno
      id: set-env
      shell: bash
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "environment=production" >> $GITHUB_OUTPUT
        else
          echo "environment=uat" >> $GITHUB_OUTPUT
        fi
      
    - name: Imprimir entorno
      shell: bash
      run: echo "El entorno es  ${{ steps.set-env.outputs.environment }}"
  
