name: CD
on:
  workflow_call:
     inputs:
      environment:
        type: string
        required: true
      tag:
        type: string
        required: true
        
jobs:
  upload-image:
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }} 
     
     env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

     steps:
      - name: Imprimir valores de entrada
        run: |
            echo "El entorno recibido es: ${{ inputs.environment }}"
            echo "El nombre de usuario de Docker es: $DOCKER_USERNAME"
          
      - name: Hacer pull de la imagen de Docker
        run: |
          docker pull $DOCKER_USERNAME/${{ inputs.tag }}
          
      - name: Desplegar
        run: |
          docker run -d -p 8080:8080  $DOCKER_USERNAME/${{ inputs.tag }}

      - name: Verificar si el contenedor está corriendo
        run: docker ps

      - name: Verificar respuesta de la app
        run: |
           sleep 40
           curl http://localhost:8080


        
