name: CD
on:
  workflow_call:
   inputs:
      image_name:
        type: string
        required: true

jobs:
  upload-image:
     runs-on: ubuntu-latest
     environment: production
     
     env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      IMAGE_NAME: ${{ inputs.image_name }}

     steps:
       - name: Imprimir
         run: |
          echo  $DOCKER_USERNAME
          echo "Image Name: $IMAGE_NAME" 
          
    #
    #     run: |
    #      docker run -d -p 8080:8080  $DOCKER_USERNAME/sample-angular-app:0.0.0

    #   - name: Verificar si el contenedor está corriendo
    #     run: docker ps

    #   - name: Verificar respuesta de la app
    #     run: |
    #       sleep 40
    #       curl http://localhost:8080


        
