name: CD
on:
  workflow_call:

jobs:
  upload-image:
     runs-on: ubuntu-latest
     environment: production
     
     env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

     steps:
       - name: Desplegar
         run: |
          docker run -d -p 8080:8080  $DOCKER_USERNAME/sample-angular-app:0.0.0

       - name: Verificar si el contenedor está corriendo
         run: docker ps

       - name: Verificar respuesta de la app
         run: |
           sleep 40
           curl http://localhost:8080


        
