name: CI
on:
  workflow_call:
  
jobs:
  build-app:
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Mandar inputs
      id: taggear_image
      uses: ./.github/actions/taggear_image
      with:
        image_name: "sample-angular-app"

    - name: Nombre del tag
      run: |
        echo IMAGE_NAME="${{ steps.taggear_image.outputs.tagged }}" 
        echo DOCKER_USERNAME = $DOCKER_USERNAME


    - name: Hacer login en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_USERNAME/${{ steps.taggear_image.outputs.tagged }} .
        docker images
        

    - name: Subir Docker image
      run: |
        docker push $DOCKER_USERNAME/${{ steps.taggear_image.outputs.tagged }}
    

      
      

