name: CI
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    environment: production

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Mandar inputs
      id: taggear_image
      uses: ./.github/actions/taggear_image
      with:
        image_name: "mi-app-angular"

    - name: Nombre del tag
      run: |
        echo IMAGE_NAME="${{ steps.taggear_image.outputs.tagged }}" >> $GITHUB_OUTPUT


    - name: Hacer login en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_USERNAME/$IMAGE_NAME .
        docker images
        

    - name: Subir Docker image
      run: |
        docker push $DOCKER_USERNAME/$IMAGE_NAME

      
      

