name: CI
on:
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: "Extraer versión"
      id: version
      shell: bash
      run: |
        version=$(jq -r '.version' ./package.json)
        echo "Image version: $version"
        echo  "version=${version}" >> $GITHUB_OUTPUT
    
    - name: Taggear imagen Docker
      id: taggear_image
      uses: ./.github/actions/taggear_image
      with:
        image_name: "mi-app-angular"
        version: "${{ steps.version.outputs.version }}"

    - name: Nombre del tag
      run: |
        echo "El nombre de la imegen: ${{ steps.taggear_image.outputs.tagged }}"

    - name: Hacer login en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


