name: CI
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

  
jobs:
  build-app:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Action tag
      id: taggear_image
      uses: ./.github/actions/taggear_image
  
    - name: Nombre del tag
      run: |
        echo IMAGE_NAME="${{ steps.taggear_image.outputs.tagged }}" >> $GITHUB_OUTPUT

       
    - name: Imprimir valores de entrada
      run: |
            echo "El entorno recibido es: ${{ inputs.environment }}"
            echo "El nombre de usuario de Docker es: $DOCKER_USERNAME"


    - name: Hacer login en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_USERNAME/${{IMAGE_NAME}} .
        docker images
        

    - name: Subir Docker image
      run: |
        docker push $DOCKER_USERNAME/${{IMAGE_NAME}}

  test-cobertura:
    needs:  build-app
    if:  ${{ inputs.environment }} == production
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar simulación de test
        run: | 
          sleep 20
          echo "Ejecutando simulación de test en producción"
        
      - name: Ejecutar cobertura de código
        run: | 
          sleep 20
          echo "Ejecutando cobertura de código en producción"
    

      
      

