name: CI
on:
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Taggear imagen Docker
      uses: 
      with:
        image_name: "mi-app-angular"
        version: "1.0.0"

    # Paso 4: Mostrar el nombre de la imagen etiquetada
    - name: Show tagged image
      run: echo "Tagged image is: ${{ steps.taggear.outputs.tagged_image }}"

