name: CI
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        
      image_name:
        type: string
        required: true
  
jobs:
  build-app:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      
      
    steps:
    - name: Imprimir valores de entrada
      run: |
            echo "El entorno recibido es: ${{ inputs.environment }}"
            echo "El nombre de usuario de Docker es: $DOCKER_USERNAME"
    
  

    - name: Nombre del tag
      id: set_image_name
      run: |
        echo IMAGE_NAME="${{ inputs.image_name }}" 
        echo "image_name=${{ inputs.image_name }}" >> $GITHUB_OUTPUT
        echo DOCKER_USERNAME = $DOCKER_USERNAME


    - name: Hacer login en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_USERNAME/${{ inputs.image_name }} .
        docker images
        

    - name: Subir Docker image
      run: |
        docker push $DOCKER_USERNAME/${{ inputs.image_name }}
    

      
      

