name: Workflow principal
on:
  workflow_dispatch:

jobs:
  call-workflow-ci:
    uses: ./.github/workflows/ci-build-push-docker-image.yaml
    secrets: inherit 

  call-workflow-cd:
    needs: call-workflow-ci

  
    runs-on: ubuntu-latest
    steps:
      - name: Verificar output CI
        run: |
          echo "Output de CI: ${{ needs.call-workflow-ci.outputs.image_name }}"
