name: Workflow principal
on:
  workflow_dispatch:

jobs:
  call-workflow-ci:
    uses: ./.github/workflows/ci-build-push-docker-image.yaml
    secrets: inherit 

  call-workflow-cd:
    needs: call-workflow-ci
    uses: ./.github/workflows/cd-deply-verify.yaml
    secrets: inherit 
    with:
      image_name: ${{ needs.call-workflow-ci.outputs.image_name }}
