name: Workflow principal
on:
  workflow_dispatch:
 

jobs:
  entorno:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir rama del push
        run: echo "El push se realizó en la rama ${{ github.ref_name }}"
      - name: Imprimir entorno
        run: |
          echo "El entorno es ${{ env.ENVIRONMENT }}"
        env:
          ENVIRONMENT: ${{ github.ref_name == 'main' && 'production' || 'uat' }}

      
#  call-workflow-ci:
#    uses: ./.github/workflows/ci-build-push-docker-image.yaml
#    secrets: inherit 

#  call-workflow-cd:
#    needs: call-workflow-ci
#    uses: ./.github/workflows/cd-deply-verify.yaml
#    secrets: inherit 
