name: Workflow principal
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development

jobs:
  entorno:
    runs-on: ubuntu
    steps:
      - name: Imprimir rama del push
        run: echo "El push se realizó en la rama ${{ github.ref_name }}"

      
#  call-workflow-ci:
#    uses: ./.github/workflows/ci-build-push-docker-image.yaml
#    secrets: inherit 

#  call-workflow-cd:
#    needs: call-workflow-ci
#    uses: ./.github/workflows/cd-deply-verify.yaml
#    secrets: inherit 
