name: Workflow principal
on:
  workflow_dispatch:
 

jobs:
  entorno:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }} 
    steps:
      - name: Imprimir rama del push
        run: echo "El push se realizó en la rama ${{ github.ref_name }}"
        
      - name: Definir entorno
        id: set-env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "environment=uat" >> $GITHUB_OUTPUT
          fi
      
      - name: Imprimir entorno
        run: echo "El entorno es  ${{ steps.set-env.outputs.environment }}"

      
  call-workflow-ci:
    needs: entorno
    uses: ./.github/workflows/ci-build-push-docker-image.yaml
    with:
      environment: ${{ needs.entorno.outputs.environment }}
    secrets: inherit 
   
  call-workflow-cd:
    needs: [entorno,call-workflow-ci]
    uses: ./.github/workflows/cd-deply-verify.yaml
    with:
      environment: ${{ needs.entorno.outputs.environment }}
    secrets: inherit 

  test-cobertura:
    needs: [entorno, call-workflow-cd]
    if:  ${{ github.ref_name }} == main
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar simulación de test
        run: echo "Ejecutando simulación de test en producción"
        
      - name: Ejecutar cobertura de código
        run: echo "Ejecutando cobertura de código en producción"
