name: Workflow principal
on:
  workflow_dispatch:
 

jobs:
  entorno:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir rama del push
        run: echo "El push se realizó en la rama ${{ github.ref_name }}"
        
      - name: Definir entorno
        id: set-env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=uat" >> $GITHUB_ENV
          fi
      
      - name: Imprimir entorno
        run: echo "El entorno es $ENVIRONMENT"

      
  call-workflow-ci:
    needs: entorno
    uses: ./.github/workflows/ci-build-push-docker-image.yaml
    secrets: inherit 

  call-workflow-cd:
    needs: call-workflow-ci
    uses: ./.github/workflows/cd-deply-verify.yaml
    secrets: inherit 

  test-cobertura:
    needs: [entorno, call-workflow-ci]
    if:  ${{ github.ref_name }} == main
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar simulación de test
        run: echo "Ejecutando simulación de test en producción"
        
      - name: Ejecutar cobertura de código
        run: echo "Ejecutando cobertura de código en producción"
