name: Workflow principal
on:
  workflow_dispatch:

env:
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

jobs:
  entorno:
    runs-on: ubuntu
    steps:
      - name: imprimir
        run: |
          echo El entorno es $ENVIRONMET
      
  call-workflow-ci:
    uses: ./.github/workflows/ci-build-push-docker-image.yaml
    secrets: inherit 

  call-workflow-cd:
    needs: call-workflow-ci
    uses: ./.github/workflows/cd-deply-verify.yaml
    secrets: inherit 
