name: Workflow principal
on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:
    

jobs:
  entorno:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Action environment
      id: environment
      uses: ./.github/actions/environment
  
    - name: Entorno
      run: |
        echo environment="${{ steps.environment.outputs.environment }}" >> $GITHUB_OUTPUT
      
  call-workflow-ci:
    needs: [entorno]
    uses: ./.github/workflows/ci-build-push-docker-image.yaml
    with:
      environment: ${{ needs.entorno.outputs.environment }}
    secrets: inherit 
   
  call-workflow-cd:
    needs: [entorno,call-workflow-ci]
    uses: ./.github/workflows/cd-deploy-verify.yaml
    with:
      environment: ${{ needs.entorno.outputs.environment }}
      tag: ${{ needs.call-workflow-ci.outputs.tag }}
    secrets: inherit 
      
 
